### ISSUE TITLE
[BUG] Correction in the Labeling of Plots in Intro to QSVT Tutorial

### ISSUE THREAD

**Issue by elucidator8918** [PennyLaneAI/qml#1028]
#### Issue description

The labels in the plot seem to be switched. The label "target" should correspond to the `target_poly` function, and the label "qsvt" should correspond to the quantum singular value transformation results. I would like to fix this by curating a PR.

* *Expected behavior:* 
  - The plot should correctly label "target" for the `target_poly` function and "qsvt" for the quantum singular value transformation results.

* *Actual behavior:* 
  - The labels are switched in the plot. "qsvt" is labeled as "target," and vice versa.

#### Source code and tracebacks

Present Incorrect Code in the Tutorial:
```python
plt.plot(a_vals, qsvt, label="target")
plt.plot(a_vals, target, "*", label="qsvt")

plt.legend()
plt.show()
```
Corrected Code:
```python
plt.plot(a_vals, target, label="target")
plt.plot(a_vals, qsvt, "*", label="qsvt")

plt.legend()
plt.show()
```
#### Tutorial Link

[Intro to QSVT Link](https://pennylane.ai/qml/demos/tutorial_intro_qsvt/)

**Comment by josh146** [comment]
Nice catch @elucidator8918! Would you like to open a PR to make this change to the demo? It is available here: https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_intro_qsvt.py

**Comment by elucidator8918** [comment]
@josh146 Yes i would love to make the PR :)

**Comment by KetpuntoG** [comment]
@elucidator8918 thanks for work on this!
