### ISSUE TITLE
[BUG] QML JAX and Optax demo does not use the correct definition of optimizer

### ISSUE THREAD

**Issue by Gopal-Dahale** [PennyLaneAI/qml#1045]
#### Issue description

In the demo "How to optimize a QML model using JAX and Optax", the `update_step_jit` does not use the correct definition of the optimizer that is defined in `optimization_jit` ([Line 170](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py#L170)) as it is not passed as an argument to the `update_step_jit` function. It possibly uses the earlier definition of the optimizer ([Line 123](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py#L123)).

* *Expected behavior:* In principle, the optimizer should get passed to the `update_step_jit` function ([Line 165-189](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_How_to_optimize_QML_model_using_JAX_and_Optax.py#L165-L189))

* *Actual behavior:* The code works fine but uses the earlier definition of the optimizer.

* *System information:* Using standard google colab.

**Comment by KetpuntoG** [comment]
Thanks for opening the issue, I look at it!

**Comment by KetpuntoG** [comment]
Solved 😄

**Comment by KetpuntoG** [comment]
The changed will be deployed in a few hours
