### ISSUE TITLE
[DEMO]

### ISSUE THREAD

**Issue by goel-67** [PennyLaneAI/qml#1081]
#### General information

**Name**
Lakshay Goel, Kovid Tandon, Anderson Xu, Yi Lin Yang

**Affiliation** (optional)
Purdue University

**Twitter** (optional)

**Image** (optional)
Suggested image to use when advertising your demo on Twitter; can be provided via hyperlink or by copy/pasting directly in GitHub.

--------------------------------------------------------------------------------

#### Demo information

**Title**
Qutrits and the Deutsch-Jozsa Algorithm

**Abstract**
This research project explores the extension of the Deutsch-Jozsa algorithm from qubits to qutrits within the realm of quantum computing. Leveraging the unique properties of qutrits—quantum systems capable of existing in three distinct states simultaneously—we investigate whether the standard implementation of the algorithm remains effective in this higher-dimensional context. By redesigning fundamental quantum gates and reconstructing the quantum circuit tailored to accommodate qutrits' distinctive characteristics, we aim to unravel insights into how this foundational algorithm behaves within a more complex quantum system. This study contributes to advancing the understanding and utilization of qutrit-based quantum computing, potentially paving the way for implementing more sophisticated algorithms and applications in quantum information processing. Additionally, it opens avenues for exploring the Deutsch-Jozsa algorithm with arbitrary qudits, expanding the scope of quantum algorithm design.

**Relevant links**
https://github.com/goel-67/Qutrits-and-the-Deutsch-Jozsa-Algorithm/blob/main/DJ_qutrits.ipynb
https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=2b8bbd69f4e682f6ce6ea7597961d26c5441f287
https://pennylane.ai/qml/demos/tutorial_qutrits_bernstein_vazirani/
https://github.com/filipecorrea/deutsch-jozsa/blob/master/deutsch-jozsa.ipynb
https://en.wikipedia.org/wiki/Deutsch%E2%80%93Jozsa_algorithm
https://www.iosrjournals.org/iosr-jap/papers/Vol10-issue6/Version-2/D1006021619.pdf

**Comment by KetpuntoG** [comment]
Awesome, Great job team!
I'll work on adding it to the website

Thanks for citing the Bernstein–Vazirani demo, I hope you found it useful 😉

**Comment by goel-67** [comment]
Thank you so much for giving us the opportunity, and we look forward to seeing our work on your website. We also found the Bernstein-Vazirani demo to be incredibly useful when using it as a reference to extend the DJ algorithm to qutrits.

Best regards,
Lakshay Goel

**Comment by ikurecic** [comment]
Congrats on the community demo, @goel-67 , very cool!

It's now live on the website [here](https://pennylane.ai/qml/demos_community/), and if you keep an eye on the PennyLane social media around 15 May, you'll see it mentioned, as well.

**Comment by ikurecic** [comment]
Updating here to say that this was completed last week, @goel-67 ! ☺

**Comment by goel-67** [comment]
Yes, that seems good!

Thanks,
Lakshay


________________________________
