### ISSUE TITLE
Addition of an author to an existing community demo

### ISSUE THREAD

**Issue by goel-67** [PennyLaneAI/qml#1087]
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/goel-67/Qutrits-and-the-Deutsch-Jozsa-Algorithm/tree/main

Delete everything above the dashed line, and fill in the template.

-------------------------------------------------------------------------------------------------------------

#### Issue description

Hi,
We wanted to add the name of our project advisor, Dr. Hadiseh Alaeian to the authors. Could you help us with making this addition as soon as possible?

**Comment by KetpuntoG** [comment]
Hi! No problem, it should be solved soon 👌

**Comment by goel-67** [comment]
[like]  Goel, Lakshay reacted to your message:
________________________________

**Comment by goel-67** [comment]
[0]     Goel, Lakshay reacted to your message:
________________________________

**Comment by goel-67** [comment]
Thank you for the prompt update!

________________________________
