### ISSUE TITLE
[DEMO] Multi-Class Quantum Convolutional Neural Networks

### ISSUE THREAD

**Issue by marcomordacci1** [PennyLaneAI/qml#1116]
#### General information

**Name**
Marco Mordacci

**Affiliation**
University of Parma

--------------------------------------------------------------------------------

#### Demo information

**Title**
Multi-Class Quantum Convolutional Neural Networks

**Abstract**
This is a demo for the paper "Multi-Class Quantum Convolutional Neural Networks".
We implemented a Quantum Convolutional Neural Networks (QCNNs) for multi-class classification.
The network is tested on the MNIST dataset, considering 4, 6, 8 and all the 10 classes.

**Relevant links**
Git repo: https://github.com/qslab-unipr/qcnn
Paper: https://arxiv.org/abs/2404.12741

**Comment by ikurecic** [comment]
Hi @marcomordacci1 , it's brilliant to see your code here!
Would you mind adding inline backticks and codeblock environments to the readme of your repository, to make it a bit easier to read through the code details?

If you'd like to share your (and/or your collaborators' or university's) social media handles for LinkedIn or Twitter/X for our Marketing Team, that would be great. Let me know.

**Comment by marcomordacci1** [comment]
Hi, of course! I will update it.

Our LinkedIn profiles are:
https://www.linkedin.com/in/marco-mordacci-811430173
https://www.linkedin.com/in/davide-ferrari-4237a259/
https://www.linkedin.com/in/micheleamoretti/

**Comment by marcomordacci1** [comment]
Hi, i have updated the readme file, let me know if there are any other issues. 
Thank you!

**Comment by CatalinaAlbornoz** [comment]
Thanks @marcomordacci1! We will review and let you know of the next steps.

**Comment by ikurecic** [comment]
Thanks a lot for the update, @marcomordacci1 , and for sharing your LinkedIn profiles!
The repository looks great. Also, if you want to make text clickable (in the first paragraph of the readme, for example), you can use this format: `[text](URL)`.

I'll make the update to the pennylane.ai website for you and our our marketing team will tag you on LinkedIn during promotion.
Really excited to give your work a bit more promo — thanks so much for sharing it.
Please feel free to reach out if you have any questions.

**Comment by marcomordacci1** [comment]
Thank you for your effort and for this great opportunity!

kind regards,
Marco
