### ISSUE TITLE
[BUG] `ComplexWarning`s in various demos

### ISSUE THREAD

**Issue by mudit2812** [PennyLaneAI/qml#1212]
#### Issue description

Many demos have complex warnings present, with some demos even having multiple complex warnings present.

**Expected behavior:** (What you expect to happen)
No warnings are expected

**Actual behavior:** (What actually happens)
The following demos have `ComplexWarning`s:
* [`tutorial_eqnn_force_field`](https://pennylane.ai/qml/demos/tutorial_eqnn_force_field/): 1 warning
* [`tutorial_here_comes_the_sun`](https://pennylane.ai/qml/demos/tutorial_here_comes_the_sun/): 1 warning
* [`tutorial_pulse_programming101`](https://pennylane.ai/qml/demos/tutorial_pulse_programming101/): 4 warnings
* [`tutorial_vqe_vqd`](https://pennylane.ai/qml/demos/tutorial_vqe_vqd/): 34 warnings (yikes)

**System information:** (include your operating system, Python version, Sphinx version, etc.)

#### Source code and tracebacks

The warnings in all demos is from jax. Example warning:
```pycon
/home/runner/work/qml/qml/venv/lib/python3.10/site-packages/jax/_src/lax/lax.py:2745: ComplexWarning: Casting complex values to real discards the imaginary part
  x_bar = _convert_element_type(x_bar, x.aval.dtype, x.aval.weak_type)
```

**Comment by KetpuntoG** [comment]
In this demo [qrom demo](https://github.com/PennyLaneAI/qml/pull/1213) too 
Also, note that the `vqe_vqd` will be published (from the marketing point of view) soon, so it would good to fix this issue if possible
