### ISSUE TITLE
[BUG] Corrections MPS demo

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/qml#1267]
Reading the MPS demo (great demo!) I found what I believe to be some typos:

Is the S correct here? It has not appear before

---

<img width="821" alt="Screenshot 2024-11-18 at 3 04 07 PM" src="https://github.com/user-attachments/assets/161e077a-bb68-4d54-860f-91d29ec2580e">

---

some deployment issue:

---

<img width="822" alt="Screenshot 2024-11-18 at 3 04 53 PM" src="https://github.com/user-attachments/assets/1aec3680-3c1f-45de-9c78-29f891f5b9cc">

---

Maybe do you want to do `Ss.append(S)`? (if that's the case check the code bellow since it is also done)

---
<img width="780" alt="Screenshot 2024-11-18 at 3 14 39 PM" src="https://github.com/user-attachments/assets/b2bf4639-bbbd-4851-9391-53c085870e59">

**Comment by Qottmann** [comment]
Thanks @KetpuntoG can you review https://github.com/PennyLaneAI/qml/pull/1269 ?
