### ISSUE TITLE
Meet the Quantum Natural Gradient with Momentum (Momentum-QNG) Optimizer

### ISSUE THREAD

**Issue by borbysh** [PennyLaneAI/qml#1274]
@ikurecic
#### General information

**Name**
Oleksandr Borysenko

**Affiliation** (optional)
National Science Center "Kharkiv Institute of Physics and Technology", 61108 Kharkiv, Ukraine

**Twitter** (optional)
Your Twitter username, if interested; helps us advertise your demo while linking directly back to you.

**Image** (optional)
[Suggested image to use when advertising your demo on Twitter; can be provided via hyperlink or by copy/pasting directly in GitHub.](https://github.com/borbysh/Momentum-QNG/blob/main/Santa.png)

--------------------------------------------------------------------------------

#### Demo information

**Title**
Meet the Quantum Natural Gradient with Momentum (Momentum-QNG) Optimizer

**Abstract**
In this demo we introduce our new Momentum-QNG optimization algorithm. We demonstrate its performance by optimizing the ground state energy of 8-qubit quantum Sherrington-Kirkpatrick model with VQE ansatz. We benchmark it together with the Momentum and basic QNG optimizers.

**Relevant links**
[Add a link to your demo (as a GitHub repository, Jupyter notebook, Python script, etc.) as well as links to any papers/resources used.](https://github.com/borbysh/Momentum-QNG/blob/main/Momentum-QNG_tutorial.ipynb)

**Comment by CatalinaAlbornoz** [comment]
Thanks @borbysh ! This looks amazing.

We'll do an internal review and get back to you within a week or so with next steps. Congrats!

**Comment by ikurecic** [comment]
This looks brilliant, @borbysh , congrats! :)

Could I ask you for a couple of small things?

1. Could you use "PennyLane" instead of "Pennylane" in the Demo? 😅
2. Do you and your coauthors (or your institute? 😉) have Twitter or LinkedIn accounts? We can link to them from the PennyLane accounts, if you'd like.

**Comment by borbysh** [comment]
I repared "PennyLane" and added some LinkedIn accounts. Now some author names are clickable

**Comment by ikurecic** [comment]
Thanks a lot, @borbysh !
I'll make sure it's live soon (either today or on Monday), and our marketing team will tag you next week as well. :)

Well done — I hope lots of people see it!

**Comment by borbysh** [comment]
Great, thank you!

пт, 6 дек. 2024 г., 18:42 Ivana Kurečić ***@***.***>:
