### ISSUE TITLE
[DEMO] Iris Classification using Angle Embedding and qml.qnn.KerasLayer

### ISSUE THREAD

**Issue by gahanh** [PennyLaneAI/qml#152]
### General information

**Name**
Hemant Gahankari

**Affiliation** (optional)
None

### Demo information

**Title**
Iris Classification using Angle Embedding and qml.qnn.KerasLayer

**Abstract**
This example is created to expalin how to pass classical data into the quantum function and convert it to quantum data. Later it shows how to create qml.qnn.KerasLayer from qnode and train it and also check model performance.

**Relevant links**
https://colab.research.google.com/drive/13PvS2D8mxBvlNw6_5EapUU2ePKdf_K53#scrollTo=1fJWDX5LxfvB

**Comment by antalszava** [comment]
The demo was added to the [community demos page](https://pennylane.ai/qml/demos_community.html).
