### ISSUE TITLE
[DEMO] Linear Regression using Angle Embedding and Single Qubit

### ISSUE THREAD

**Issue by gahanh** [PennyLaneAI/qml#155]
#### General information

**Name**
Hemant Gahankari

**Affiliation** (optional)
None
--------------------------------------------------------------------------------

#### Demo information

**Title**
Linear Regression using Angle Embedding and Single Qubit with qml.qnn.KerasLayer

**Abstract**
This example is created to explain how to create a Hybrid Neural Network (Mix of Classical and Quantum Layer) and train it and get predictions from it.

The data set consists of a temperature readings in Degree Centigrade and corresponding Fahrenheit.

Objective is to train a neural network to predict Fahrenheit value given Deg Centigrade value.

**Relevant links**
https://colab.research.google.com/drive/1ABVtBjwcGNNIfmiwEXRdFdZ47K1vZ978?usp=sharing

**Comment by antalszava** [comment]
The demo was added to the [community demos page](https://pennylane.ai/qml/demos_community.html).
