### ISSUE TITLE
[DEMO]  Quantum Machine Learning Model Predictor for Continuous Variable

### ISSUE THREAD

**Issue by roberth2018** [PennyLaneAI/qml#187]
#### General information

**Name**
Roberth Saénz Pérez Alvarado.

**Affiliation** (optional)
UNIVERSIDAD NACIONAL DE INGENIERIA ( UNI , LIMA-PERU).
--------------------------------------------------------------------------------

#### Demo information

**Title**
Quantum Machine Learning Model Predictor for Continuous Variable

**Abstract**
According to this paper: "Predicting toxicity by quantum machine learning" (Teppei Suzuki, Michio Katouda 2020)  is possible to predict continuous variables like continuous-variable quantum neural network model described in Killoran et al. (2018), using 2 qbits per feature applying encodings, variational circuits and some lineal transformations on expected values in order to predict values close to real target. I uploaded the following example from https://pennylane.ai/qml/demos/quantum_neural_net using PennyLane libraries, a short dataset which consists on 1 dimensional feature and 1 output, so that the processing does not take too much time, the algorithm showed reliable results.

**Relevant links**
https://github.com/roberth2018/Quantum-Machine-Learning/blob/main/Quantum_Machine_Learning_Model_Predictor_for_Continuous_Variable_.ipynb
https://pennylane.ai/qml/demos/quantum_neural_net.html
https://arxiv.org/abs/2008.07715
https://arxiv.org/abs/1806.06871

**Comment by josh146** [comment]
Thanks @roberth2018 for your contribution! Someone from the team will get back to you shortly.

**Comment by co9olguy** [comment]
Hi @roberth2018!

I've made your demo into a card for website. Before posting it there, I wanted to run it by you, as I have made some moderate edits to fix typos and tidy up the English: 
![image](https://user-images.githubusercontent.com/7213358/102657611-f9883680-4143-11eb-875d-fdc0314da842.png)

**Comment by co9olguy** [comment]
Has now been merged and should be visible online shortly, thanks @roberth2018!
