### ISSUE TITLE
Add bylines to demos

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/qml#200]
Add bylines to the demos with the following information:
 - original publication date
 - date of most recent update (if any)
 - author ("PennyLane team", or external contributor where applicable)
 - PennyLane version

For the PL version, must decide if we should add version of most recent build, original version, or a range of versions for which this demo will work (like ">=0.11" or something).

**Comment by josh146** [comment]
Thoughts:

* Should we only add PennyLane version for demos we know _don't_ work with the latest PL? I figure that there is always an assumption that demos/tutorials work with the latest version.

**Comment by josh146** [comment]
Funnily enough, this should work:

```console
pip install -r https://raw.githubusercontent.com/PennyLaneAI/qml/master/requirements.txt
```

But, it will install EVERYTHING. Torch, TensorFlow, Jax, plugins, Qiskit, PyQuil, and so on 😆

**Comment by glassnotes** [comment]
Closing as the bylines were added as part of #203; in terms of the requirement info, that can be handled as part of #201 :+1:
