### ISSUE TITLE
[DEMO] QCNN for Speech Recognition and Neural Saliency Analysis

### ISSUE THREAD

**Issue by huckiyang** [PennyLaneAI/qml#219]
#### General information

**Name**
C.-H. Huck Yang

**Affiliation** 
Georgia Institute of Technology, Atlanta, GA

--------------------------------------------------------------------------------

#### Demo information

**Title**
QCNN for Speech Commands Recognition.

**Abstract**
We provide a hybrid model training with larger-scale acoustic features 3,000 to 10,000 with quantum convolution networks with Random layer, which still provide insightful convolution features without the encoding time cost from the CPU simulation and on the request queueing time from QPU. We further provide classical activation mapping, a neural saliency analysis, on the well-trained neural models (QCNN Self-Attention v.s. CNN Self-Attention) to justify that the QCNN Self-attention model did learn meaningful representations. An additional Connectionist Temporal Classification (CTC) loss on character recognition is also provided for continuous speech recognition. 

**Relevant links**

We provide a GitHub [repo](https://github.com/huckiyang/QuantumSpeech-QCNN) and [Colab](https://colab.research.google.com/drive/11Yi53W6-Z-uW84A8Sr6OqOMlBIel1PKM?usp=sharing) for future studies. A related [preprint](https://arxiv.org/pdf/2010.13309.pdf) has been released and will appear in IEEE International Conference on Acoustics, Speech, & Signal Processing ([ICASSP](https://scholar.google.com/citations?view_op=top_venues&hl=en&venue=HHC6AUo36fEJ.2020&vq=phy_acousticssound)) 2021.

```bib
@article{yang2020decentralizing,
  title={Decentralizing Feature Extraction with Quantum Convolutional Neural Network for Automatic Speech Recognition},
  author={Yang, Chao-Han Huck and Qi, Jun and Chen, Samuel Yen-Chi and Chen, Pin-Yu and Siniscalchi, Sabato Marco and Ma, Xiaoli and Lee, Chin-Hui},
  journal={arXiv preprint arXiv:2010.13309},
  year={2020}
}
```

**Comment by trbromley** [comment]
Thanks @huckiyang for this nice contribution!

A member of the team will have a look some time during this week :slightly_smiling_face:

**Comment by trbromley** [comment]
Thanks @huckiyang for the contribution! Your demo is now visible on the [community demos](https://pennylane.ai/qml/demos_community.html) page! :100: :rocket:

**Comment by trbromley** [comment]
Hi @huckiyang, I'd like to consider rewording the abstract slightly. Would the following work for you:

> We train a hybrid quantum convolution neural network (QCNN) on acoustic data with up to 10,000 features. This model uses layers of random quantum gates to efficiently encode convolutional features. We perform a neural saliency analysis to provide a classical activation mapping to compare classical and quantum models, illustrating that the QCNN self-attention model did learn meaningful representations. An additional connectionist temporal classification (CTC) loss on character recognition is also provided for continuous speech recognition.

**Comment by huckiyang** [comment]
Hi @trbromley Thank you Tom, it looks good to me. Many thanks for the editing efforts.
