### ISSUE TITLE
[DEMO] Variational Quantum Circuits for Deep Reinforcement Learning

### ISSUE THREAD

**Issue by ycchen1989** [PennyLaneAI/qml#220]
#### General information

**Name**
Samuel Yen-Chi Chen

**Affiliation** 
Brookhaven National Laboratory, Upton NY

--------------------------------------------------------------------------------

#### Demo information

**Title**
Variational Quantum Circuits for Deep Reinforcement Learning

**Abstract**
This work explores variational quantum circuits for deep reinforcement learning. Specifically, we reshape classical deep reinforcement learning algorithms like experience replay and target network into a representation of variational quantum circuits. Moreover, we use a quantum information encoding scheme to reduce the number of model parameters compared to classical neural networks. To the best of our knowledge, this work is the first proof-of-principle demonstration of variational quantum circuits to approximate the deep Q-value function for decision-making and policy-selection reinforcement learning with experience replay and target network. Besides, our variational quantum circuits can be deployed in many near-term NISQ machines.

**Relevant links**
We provide a GitHub [repo](https://github.com/ycchen1989/Var-QuantumCircuits-DeepRL) for future studies. The paper has been accepted by IEEE Access and can be downloaded [here](https://ieeexplore.ieee.org/abstract/document/9144562).

```bib
@article{chen19,
title={Variational quantum circuits for deep reinforcement learning},
  author={Chen, Samuel Yen-Chi and Yang, Chao-Han Huck and Qi, Jun and Chen, Pin-Yu and Ma, Xiaoli and Goan, Hsi-Sheng},
  journal={IEEE Access},
  year={2020},
  volume={8},
  pages={141007-141024},
  publisher={IEEE}
}
```

**Comment by josh146** [comment]
Thanks @ycchen1989 for this great contribution!

A member of the team will get back to you sometime during this week for a demo review 🙂

**Comment by trbromley** [comment]
Thanks @ycchen1989  for the contribution! Your demo is now visible on the [community demos](https://pennylane.ai/qml/demos_community.html) page! :100: :rocket:
