### ISSUE TITLE
[DEMO] Feature maps for kernel-based quantum classifiers

### ISSUE THREAD

**Issue by SemyonSinchenko** [PennyLaneAI/qml#221]
#### General information

**Name**
Semyon Sinchenko

**Affiliation** (optional)
Moscow State University

--------------------------------------------------------------------------------

#### Demo information

**Title**
Feature maps for kernel-based quantum classifiers

**Abstract**
In this tutorial we implement a few examples of feature maps for kernel based quantum machine learning. We'll see how quantum feature maps could make linear unseparable data separable after applying a kernel and measuring observable. We will follow an [https://arxiv.org/abs/1906.10467](https://arxiv.org/abs/1906.10467) article and also implement with PennyLane all the kernel-functions from this article.

**Relevant links**
https://github.com/SemyonSinchenko/PennylaneQuantumFeatureMaps
https://arxiv.org/abs/1906.10467

**Comment by josh146** [comment]
Thanks @SemyonSinchenko for this nice contribution!

A member of the team will have a look some time during this week 🙂

**Comment by Thenerdstation** [comment]
Thanks @SemyonSinchenko, I'll open a PR to add this to the community page.

**Comment by trbromley** [comment]
Thanks @SemyonSinchenko for the contribution! Your demo is now visible on the [community demos](https://pennylane.ai/qml/demos_community.html) page! :100: :rocket:
