### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ixfoduap** [PennyLaneAI/qml#228]
The collection of PennyLane demos is amazing! Yet as it continues to grow, it's becoming difficult to find specific demos. We have a nice structure organizing them into categories, and useful filters for specific topics, both of which are very helpful. Yet it often still takes time to locate specific tutorials.

Adding a search bar to the page would make it much easier to navigate and to quickly identify the location of specific demos. For example, where do I find demos on barren plateaus? On kernel methods? On VQE in different spin sectors? 

![Screenshot from 2021-03-08 17-05-16](https://user-images.githubusercontent.com/40441298/110388566-425bd700-8031-11eb-9492-e275fbbe9cb2.png)

**Comment by josh146** [comment]
This should be quite easy to do - we are actually hiding the search bar which is automatically added via sphinx!

In fact, it should be possible to get to the search page still: https://pennylane.ai/qml/search.html

Weirdly, though, the search isn't working for me 🤔

**Comment by josh146** [comment]
Okay, I can't get the PL _nor_ the SF docs search working either:

https://pennylane.readthedocs.io/en/stable/search.html?q=backpropagation

Does it work for anyone else? Both were working for me during QHack, as I was using it to search for functions.

**Comment by co9olguy** [comment]
It still works, but it seems to be picky about which queries it will return results for (e.g., try `rot`). I don't think it's a general-purpose search

**Comment by josh146** [comment]
Weird, none of the search pages are working for me, in both chrome and firefox 🤔

**Comment by glassnotes** [comment]
Closing this as the search bar is now live :tada:
