### ISSUE TITLE
[DEMO] Meta-Variational Quantum Eigensolver

### ISSUE THREAD

**Issue by nahumsa** [PennyLaneAI/qml#238]
#### General information

**Name**
Nahum Sá

**Affiliation** (optional)
Centro Brasileiro de Pesquisas Físicas

--------------------------------------------------------------------------------

#### Demo information

**Title**
Meta-Variational Quantum Eigensolver

**Abstract**
In this tutorial I follow [Meta-VQE paper](https://arxiv.org/abs/2009.13545). The Meta-VQE algorithm is a variational quantum algorithm that is suited for NISQ devices and encodes parameters of a Hamiltonian into a variational ansatz which we can obtain good estimations of the ground state of the Hamiltonian by changing only those encoded parameters. 

**Relevant links**
Demo - https://github.com/nahumsa/pennylane-notebooks/blob/main/Meta-VQE%20Pennylane.ipynb
Original Paper - https://arxiv.org/abs/2009.13545
Alba Cervera-Lierta QHACK21 repository - https://github.com/AlbaCL/qhack21/blob/main/Meta-VQE.ipynb

**Comment by co9olguy** [comment]
Thanks for the contribution @nahumsa! I'll put together a new card for your project shortly and share with you before adding to the site

**Comment by co9olguy** [comment]
Hi @nahumsa, I've created a new [PR](https://github.com/PennyLaneAI/qml/pull/239) to add your demo to the site (with some light editing for grammar). You can see a preview here: 
![image](https://user-images.githubusercontent.com/7213358/112875708-8707ea80-9092-11eb-94a5-342915939883.png)

Also, if you have any suggested images for us to use when advertising your tutorial on social media, feel free to share

**Comment by nahumsa** [comment]
Awesome, thanks!
I don't have any suggested images, feel free to choose.

**Comment by co9olguy** [comment]
Great, thanks for the submission @nahumsa! We'll advertise it shortly :slightly_smiling_face:

**Comment by co9olguy** [comment]
Thanks again @nahumsa, it's out in the wild  now
