### ISSUE TITLE
[BUG] Pennylane Tutorial Search Bar

### ISSUE THREAD

**Issue by sylviemonet** [PennyLaneAI/qml#301]
-------------------------------------------------------------------------------------------------------------

#### Issue description

Description of the issue - Can not get the full search bar on safari.

<img width="1440" alt="searchBar" src="https://user-images.githubusercontent.com/16817699/124407940-b0ae6d00-dd77-11eb-8198-8537803c5b25.png">

* *Expected behavior:* Get the full search bar.

* *Actual behavior:* 75% search bar...

* *System information:* Nohting.

#### Additional information

Don not know if it is only an issue on macOS Big Sur (11.4 Ver.) or not.

**Comment by josh146** [comment]
@AndrewGardhouse could this be related to screen/window width?

**Comment by AndrewGardhouse** [comment]
@josh146 It looked like this issue came up from how Chrome and Safari calculated `width: auto` differently. I just opened https://github.com/PennyLaneAI/qml/pull/302 to fix this

**Comment by AndrewGardhouse** [comment]
https://github.com/PennyLaneAI/qml/pull/302 has been merged to `master`
