### ISSUE TITLE
[DEMO] EVA (Exponential Value Approximation) algorithm

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/qml#310]
#### General information

**Name**
Guillermo Alonso-Linaje.

**Affiliation** (optional)
Universidad de Valladolid.

**Twitter** (optional)
@KetPuntoG

**Image** (optional)
https://github.com/KetpuntoG/EVA_Tutorial/blob/main/eva.png

--------------------------------------------------------------------------------

#### Demo information

**Title**
EVA (Exponential Value Approximation) algorithm.

**Abstract**
VQE is currently one of the most widely used algorithms for optimizing problems using quantum computers. A necessary step in this algorithm is calculating the expectation value given a state, which is calculated by decomposing the Hamiltonian into Pauli operators and obtaining this value for each of them. In this work, we have designed an algorithm capable of figuring this value using a single circuit. A time cost study has been carried out, and it has been found that in certain more complex Hamiltonians, it is possible to obtain a good performance over the current methods.

**Relevant links**
Demo: https://github.com/KetpuntoG/EVA_Tutorial/blob/main/EVA.ipynb
Paper: https://arxiv.org/abs/2106.08731

**Comment by antalszava** [comment]
Hi @KetpuntoG, thank you for the submission!

We'll be creating a new card for your project and reaching out to check that its proposed look works with you. :+1:

**Comment by josh146** [comment]
Thanks @KetpuntoG! And just wanted to say, awesome illustrations in the notebook 🤩

**Comment by KetpuntoG** [comment]
Thanks @antalszava @josh146 !! 
I hope the notebook is well understood 😊

**Comment by antalszava** [comment]
Hi @KetpuntoG, we've got a new PR adding your contribution to the list of community demos. The card for it would look like this:
![Screenshot from 2021-07-30 19-46-58](https://user-images.githubusercontent.com/24476053/127692611-b0d32fc3-0d00-4596-be23-50b015473d91.png)

Let us know if you'd like something to be adjusted! Further thanks for the additional info, we'll be able to use those when advertising on social media. :slightly_smiling_face:

**Comment by KetpuntoG** [comment]
I think it's perfect @antalszava ! A pleasure to contribute to the community 😄

**Comment by antalszava** [comment]
Hi @KetpuntoG, we've just merged in the PR that adds your contribution. Thank you again for posting! :tada: :heart_eyes:

**Comment by KetpuntoG** [comment]
Cool @antalszava ! It's perfect 😊
