### ISSUE TITLE
Quantum Hybird Circuits for TRPO/PPO based on policy RL  [DEMO]

### ISSUE THREAD

**Issue by abhilash1910** [PennyLaneAI/qml#314]
#### General information

**Name**
Abhilash Majumder (abhilash1910-Github).

**Affiliation** (optional)
MSCI Inc.

**Twitter** (optional)
abhilash1396

**Image** (optional)
Suggested image to use when advertising your demo on Twitter; can be provided via hyperlink or by copy/pasting directly in GitHub.
https://user-images.githubusercontent.com/30946547/127306307-492184f3-a01b-46e4-a42a-6d10e320bb38.png
--------------------------------------------------------------------------------

#### Demo information

**Title**
Quantum PPO/TRPO- Taking gradients through experiments: LSTMs and memory proximal policy optimization for black-box quantum control
**Abstract**
Reinforcement Learning as quantum control leverages QHC for creating optimizations for on policy networks for Deep RL. Policy-gradient-based reinforcement learning (RL) algorithms are well suited for optimizing the variational parameters of QAOA in a noise-robust fashion, opening up the way for developing RL techniques for continuous quantum control. This is advantageous to help mitigate and monitor the potentially unknown sources of errors in modern quantum simulators.This demo aims to provide an implementation of PPO on policy algorithm with QHC (hybrid circuits) for continuous control.

**Relevant links**
https://colab.research.google.com/drive/1wkZpEpOuZHUdI-vRxQAiDlQD455diFSs?usp=sharing

**Comment by antalszava** [comment]
Hi @abhilash1910, thank you for posting! :slightly_smiling_face: 

We'll have a new card for your submission and double-check before shooting it live that it works with you. :+1:

**Comment by antalszava** [comment]
Hi @abhilash1910, we've made an addition to have the demo in. The card description would be like:

![Screenshot from 2021-08-11 13-27-04](https://user-images.githubusercontent.com/24476053/129075355-7b1f7909-c66f-4743-8d08-bda6979f4083.png)

How is it looking?

**Comment by abhilash1910** [comment]
Hi @antalszava , this looks great! 💯

**Comment by antalszava** [comment]
Hi @abhilash1910, with #316 merged, your tutorial will be going live! Thank you for your contribution! :tada: :heart_eyes:
