### ISSUE TITLE
[DEMO] Subspace Search Variational Quantum Eigensolver

### ISSUE THREAD

**Issue by LegacYFTw** [PennyLaneAI/qml#322]
#### General information

**Name**
Shah Ishmam Mohtashim
Turbasu Chatterjee
Arnav Das

**Twitter** (optional)
@IshmamShah
@Turbasu_Chatt
@arnavdas88

--------------------------------------------------------------------------------

#### Demo information

**Title**
Subspace Search Variational Quantum Eigensolver

**Abstract**
The variational quantum eigensolver (VQE) is an algorithm for searching the ground state of a quantum system. The SSVQE uses a simple technique to find the excited energy states by transforming the |0⋯0⟩ to the ground state, and another orthogonal basis state |0⋯1⟩ to the first excited state and so on. As a demonstration, the weighted SSVQE is used to find out the excited states of a Transverse Ising model with 4 spins and that of the Hydrogen molecule.

**Relevant links**
https://github.com/LegacYFTw/SSVQE
https://arxiv.org/abs/1810.09434

**Comment by mariaschuld** [comment]
Thanks so much for the demo, it was added to the community demo page and should be live soon!

**Comment by albi3ro** [comment]
@LegacYFTw  .  The website is updated. You can see your entry at https://pennylane.ai/qml/demos_community.html

Thanks for the contribution 🎉
