### ISSUE TITLE
Quantum circuit learning to compute option prices and their sensitivities

### ISSUE THREAD

**Issue by ta641** [PennyLaneAI/qml#333]
#### General information

**Name**
Takayuki Sakuma

**Affiliation** (optional)
Soka University

**Twitter** (optional)
Your Twitter username, if interested; helps us advertise your demo while linking directly back to you.

**Image** (optional)
Suggested image to use when advertising your demo on Twitter; can be provided via hyperlink or by copy/pasting directly in GitHub.

--------------------------------------------------------------------------------

#### Demo information

**Title**
Quantum circuit learning to compute option prices and their sensitivities

**Abstract**
Quantum circuit learning is applied to computing option prices and their sensitivities. The advantage of this method is that a suitable choice of quantum circuit architecture makes it possible to compute the sensitivities analytically by applying parameter-shift rules. 

**Relevant links**
link to demo
https://github.com/ta641/option_QCL/blob/master/qclop_tutorial.ipynb

link to paper
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3922040
[SSRN-id3922040.pdf](https://github.com/PennyLaneAI/qml/files/7178214/SSRN-id3922040.pdf)

**Comment by CatalinaAlbornoz** [comment]
Thank you @ta641 ! This demo looks great. I will review it in detail and come back to you. Great job!

**Comment by ta641** [comment]
Thank you very much!


2021年9月21日(火) 23:41 CatalinaAlbornoz ***@***.***>:
