### ISSUE TITLE
[DEMO] Hybrid MNIST Classification Model

### ISSUE THREAD

**Issue by sophchoe** [PennyLaneAI/qml#342]
#### General information

**Name**
Sophie Choe

**Affiliation** (optional)
Portland State University

--------------------------------------------------------------------------------

#### Demo information

**Title**
Hybrid MNIST Classification Model

**Abstract**
Keras-Pennylane hybrid model for MNIST classification, inspired by the Supervised learning with hybrid networks in "Continuous-variable quantum neural networks". 

**Relevant links**
https://github.com/sophchoe/Hybrid-Quantum-Classical-MNIST-Classfication-Model
https://arxiv.org/pdf/1806.06871v1.pdf

**Comment by josh146** [comment]
Hi @sophchoe, thank you for this submission! I member of our team will be in touch shortly after reviewing 🙂

**Comment by CatalinaAlbornoz** [comment]
Hi @sophchoe. This demo is up too! You can see it here https://pennylane.ai/qml/demos_community.html
Thank you for this contribution 😄. We will make a tweet in a few hours to promote both demos so feel free to share it with your network.

**Comment by sophchoe** [comment]
Wow, great page! I wanted to work on Quanvolutional neural network and I see a code there. Maybe I can combine with QNN layers and try on MNIST and Cifar10. Thank you!
