### ISSUE TITLE
[BUG] Can't save a Pennylane-Tensorflow hybrid model

### ISSUE THREAD

**Issue by sophchoe** [PennyLaneAI/qml#343]
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/XanaduAI/qml/issues

Delete everything above the dashed line, and fill in the template.

-------------------------------------------------------------------------------------------------------------

#### Issue description

For a Keras-Pennylane hybrid model, model.save() doesn't work and suggests to use raises x.shape as opposed to  len(x). Since it's not in my code, I am assuming it's in Pennylane Tensorflow plug-in.

* *Expected behavior:* save my trained model

* *Actual behavior:* didn't save and asked me to use x.shape instead of len(x)

* *System information:* MacOS, Python 3.8.5

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by josh146** [comment]
Hi @sophchoe! Thanks for reporting this.

As this is a bug in PennyLane, and not the tutorials, I recommend re-opening this in the [PennyLane issue tracker](https://github.com/PennyLaneAI/PennyLane/issues). That will make it visible to the main PennyLane developers, who will be able to fix the bug 🙂 

> For a Keras-Pennylane hybrid model, model.save() doesn't work

In this case, however, I can provide a bit more information --- unfortunately, the `qml.qnn.KerasLayer` class does not yet support `model.save()`. This is something we are actively looking into, however!

**Comment by josh146** [comment]
> Thank you, Josh! Since you guys are working on it, should I just not worry about posting?

Not at all, it would be super useful to post it 🙂 This is for a couple of reasons:

- It spreads awareness to other contributors as well
- It lets the core developers know that this is a feature that is important to PennyLane users :)
