### ISSUE TITLE
[FEATURE] Update VQE with Parallel QPUs demo to use Dask explicitly and remove qml.ExpvalCost

### ISSUE THREAD

**Issue by Jaybsoni** [PennyLaneAI/qml#344]
As part of a demo update (#330), we came across a [demo](https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_vqe_parallel.py) which requires a little more work in order to update. 

In this demo, we would like to replace the instances of `qml.ExpvalCost` with `qml.expval(H)` while preserving the ability to compute each term in the hamiltonian in parallel using Dask. 

Updating this demo would involve making the necessary changes to the code to remove the instance of `qml.ExpvalCost`, preserve the multiprocessing via Dask, and include a paragraph explaining to users how they can make use of Dask parallelization to optimize their projects.

**Comment by KetpuntoG** [comment]
Hey @Jaybsoni , it has been already solve right? (new link to the `[demo](https://pennylane.ai/qml/demos/vqe_parallel.html)`)
