### ISSUE TITLE
[DEMO] Fraud Detection

### ISSUE THREAD

**Issue by sophchoe** [PennyLaneAI/qml#347]
#### General information

**Name**
Sophie Choe

--------------------------------------------------------------------------------

#### Demo information

**Title**
Fraud Detection

**Abstract**
Binary classification of credit card fraudulent transactions using Keras and Pennylane

**Relevant links**
https://github.com/sophchoe/Binary_Classification_Pennylane_Keras/blob/main/fraud_detection_Pennylane_Keras.ipynb

**Comment by CatalinaAlbornoz** [comment]
Wow @sophchoe! This is amazing! Thank you for contributing this new Demo!

**Comment by sophchoe** [comment]
Please let me know if you want me to create synthetic fraudulent data to increase the sample size.

**Comment by CatalinaAlbornoz** [comment]
Hi @sophchoe, I don't think you need any additional data. The algorithm is running nicely with the current dataset you're using! I was thinking though that it may be useful for others if the abstract was a little more detailed. Do you mind adding a little more explanation to the abstract? Thanks!

**Comment by sophchoe** [comment]
Hi Catalina,

I went more detailed with Readme. Let me know if you want me to elaborate further on the cutoff dimension concept. Thank you for all your feedback.

**Comment by sophchoe** [comment]
I additionally added a couple lines in the Jupiter notebook file as well.

**Comment by CatalinaAlbornoz** [comment]
This is great! Thank you @sophchoe. I hope we can put it up on the page today.

**Comment by CatalinaAlbornoz** [comment]
Hi @sophchoe, the demo is up! We will tweet about it on Thursday. Congratulations!!

**Comment by sophchoe** [comment]
Thank you so much for all your help, Catalina!

**Comment by CatalinaAlbornoz** [comment]
It was a pleasure! Thanks to you for creating this great content.
