### ISSUE TITLE
[DEMO] Exploring quantum models with a teacher-student scheme 

### ISSUE THREAD

**Issue by KaterinaGratsea** [PennyLaneAI/qml#383]
#### General information

**Name**
Katerina Gratsea and Patrick Huembeli

**Affiliation** (optional)
Your affiliation, if applicable; e.g. University, research institute, company.

**Twitter** (optional)
AGratsea and PHuembeli

**Image** (optional)
https://drive.google.com/file/d/18o5UB3Mmb7x9HiF3C9su9m6YDLkNkLD8/view?usp=sharing

--------------------------------------------------------------------------------

#### Demo information

**Title**
Exploring quantum models with a teacher-student scheme.

**Abstract**
Using PennyLane, we introduce a teacher-student scheme to systematically compare different QNN architectures and to evaluate their relative expressive power. This scheme avoids training with a specific dataset and compares the learning capacity of different quantum models.

**Relevant links**
https://github.com/KaterinaGratsea/Teacher-student_scheme
https://arxiv.org/abs/2105.01477

**Comment by CatalinaAlbornoz** [comment]
Thank you @KaterinaGratsea! I will be reviewing it next week and I'll let you know when it's up in the page!

**Comment by KaterinaGratsea** [comment]
Perfect, thanks!

**Comment by CatalinaAlbornoz** [comment]
Hi @KaterinaGratsea, congratulations on your Demo! It was very interesting to read and it ran without any errors. It should be up in the page by tomorrow so I'll let you know when it's there. This is really impressive work!

**Comment by CatalinaAlbornoz** [comment]
I will send you your Quantum Carnival ticket on a private message on Discord 😄 .

**Comment by KaterinaGratsea** [comment]
Thanks! Happy to hear that!

Looking forward to seeing it on the page.

Cheers,

Katerina

**Comment by CatalinaAlbornoz** [comment]
Hi @KaterinaGratsea. The demo is up in the [page](https://pennylane.ai/qml/demos_community.html)! We will promote it in the next few days.

Thank you for this amazing contribution!

**Comment by co9olguy** [comment]
Now live, thanks for the submission @KaterinaGratsea!
