### ISSUE TITLE
[BUG] Update `qml.draw()` across demos.

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/qml#394]
In the latest version of PennyLane, `qml.draw()` defaults to drawing the QNode as is, without expanding templates.

However, some of the demos (including `tutorial_qaoa_intro.py`) use the circuit drawer to show how templates are expanded on devices.

Where applicable, demos should be updated to use `qml.draw(qnode, expansion_strategy="device")` if it is required. Note that demos that draw circuits without templates likely don't need this change.

**Comment by KetpuntoG** [comment]
Can we consider the issue as resolved? @antalszava
