### ISSUE TITLE
[BUG] Quantum transfer learning on IBM backend

### ISSUE THREAD

**Issue by Alex-259** [PennyLaneAI/qml#426]
#### Issue description
Hello, 

first thanks for the wonderful notebook "Quantum transfer learning". It is really amazing.
I tried it and it works quite fine, when using `dev = qml.device('default.qubit', wires=n_qubits)` as device.

However, if I test it on an actual IBM machine (e.g. ibm_cairo) it does not work or runs for days.
The queue time is not the problem maybe rather some other issues. I also tested it on some of the other IBM backends.
But the result was all the same.

When calling the `train_model` command quite at the end of the notebook, it arises the following UserWarning:

```
Resynthesized 

<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7f971b2d50d0>
<qiskit.circuit.library.standard_gates.sx.SXGate object at 0x7f971b2d5310>
<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7f9730849fd0>
<qiskit.circuit.library.standard_gates.sx.SXGate object at 0x7f971b327fd0>

and got

<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7f971b327690>
<qiskit.circuit.library.standard_gates.sx.SXGate object at 0x7f971b327410>
<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7f971b327e50>
<qiskit.circuit.library.standard_gates.sx.SXGate object at 0x7f971b327610>
<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x7f971b3276d0>

but the original was native (for ['id', 'rz', 'sx', 'x', 'cx', 'reset']) and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)
```
Maybe this is in some sense the reason for it, but I do not know.

I want to get something similar to the paper [Transfer learning in hybrid classical-quantum neural networks](https://arxiv.org/abs/1912.08278), where they showed it with the ibmqx4 backend and a execution time of 26 seconds for the full dataset.

Has somebody an idea how to fix this problem?

My system information:

Qiskit Software | Version
-- | --
qiskit-terra | 0.18.3
qiskit-aer | 0.9.0
qiskit-ignis | 0.6.0
qiskit-ibmq-provider | 0.16.0
qiskit-aqua | 0.9.5
qiskit | 0.30.1

Python | 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0]
-- | --
OS | Linux
CPUs | 12
Memory (Gb) | 62.85524368286133
Fri Feb 18 18:53:45 2022 CET

**Comment by CatalinaAlbornoz** [comment]
Hi @Alex-259, at a first glance this looks like a problem with Qiskit. See how at the end of your error message they say: "This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose ". 

Some workaround for now could be using a Mock backend. In this [error mitigation demo](https://pennylane.ai/qml/demos/tutorial_error_mitigation.html), in the _Mitigating noisy circuits in quantum chemistry_ section, you will see that we use the "FakeLima" device to simulate a noisy device. 

Please let me know if this helps solve your problem!

**Comment by Alex-259** [comment]
Hi @CatalinaAlbornoz, thanks for the reply. 

Everything works fine on the qasm_simulator or on the fake backends.
The fake backends are good to see that in theory, it works even with errors. However, I am mostly interested in the results of the real backends. I just thought that maybe someone here has already encountered the same problem. 

I will also post the question at qiskit and keep you here up to date, on how the problem can be circumvented

**Comment by PCesteban** [comment]
> Hi @CatalinaAlbornoz, thanks for the reply. 
> 
> Everything works fine on the qasm_simulator or on the fake backends.
> The fake backends are good to see that in theory, it works even with errors. However, I am mostly interested in the results of the real backends. I just thought that maybe someone here has already encountered the same problem. 
> 
> I will also post the question at qiskit and keep you here up to date, on how the problem can be circumvented 

Hi @Alex-259, I faced a similar problem running my experiments on a real backend, and indeed it took a ridiculously amount of time to finish the task, however at the end the results were returned. I also think that that's an issue that needs to be addressed.

**Comment by josh146** [comment]
Thanks @Alex-259 and @PCesteban for reporting this! We will investigate and see what the cause could be. One quick question: when you are submitting the jobs for execution, do you see them in the job queue using the IBMQ web interface? If so, what is the status of these jobs?

**Comment by Alex-259** [comment]
Hello,

yes, I see the jobs in the queue. First, I have the error messages from above two times in the notebook even before the job runs on the real backend (I think the error messages come from the transpiler step). Then, I see my job in the queue as normal. I receive the results as far as I see (jobs are completed) and then for the next job the same procedure again.

I have executed over 300 jobs this way on the real backend (e.g. ibm_cairo), but I didn't even get an update on the iteration like `Phase: train Epoch: 1/... Iter: 1/... Batch time: ...`. Only a lot of error messages.

I don't know if this helps, but for example, the id of one job on `ibm_cairo` was for example `62128d6161cbfc9d5162e026`

**Comment by Alex-259** [comment]
Hi @rmoyard,

I tested what you mentioned. That is what I get. So, only execution and shots as an outcome
![result](https://user-images.githubusercontent.com/60505803/155288080-19e49b39-f0fa-49b8-9ec0-3b4762c4534d.png)

When I look at the IBM website https://quantum-computing.ibm.com/jobs/ I see the following for the job:
![result2](https://user-images.githubusercontent.com/60505803/155287852-dfb00d3d-270c-4875-914e-84680ffd3ffc.png)
Thus, a quite low validating and queue time, but a quite large running time for this simple example

**Comment by rmoyard** [comment]
What are your PennyLane and PennyLane-Qiskit version?

Thank you for sharing the different times number, in my opinion this issue is on Qiskit/Hardware side. PennyLane-Qiskit is just a way to translate the original PennyLane circuit to a Qiskit circuit. When the translation is done, we do not control what happens on the hardware side. What you can do on PennyLane side is changing the circuit, reducing the number of shots or give some transpiler configuration that can eventually optimized your circuit.

**Comment by Alex-259** [comment]
Hi @rmoyard,

thanks for the answer.
Both are on the current version `0.21.0`.
I try to figure out what's going wrong on the hardware side and let you know here
