### ISSUE TITLE
Implementing a unitary quantum perceptron with quantum computing

### ISSUE THREAD

**Issue by KaterinaGratsea** [PennyLaneAI/qml#430]
#### General information

**Name**
Katerina Gratsea

**Affiliation** (optional)
ICFO

**Twitter** (optional)
@AGratsea

**Image** (optional)
![Screenshot from 2022-02-25 21-34-48](https://user-images.githubusercontent.com/45763333/155799227-5ad689ae-ea3d-4b48-a7d2-93c06a03c1a6.png)

--------------------------------------------------------------------------------

#### Demo information

**Title**
Implementing a unitary quantum perceptron with quantum computing

**Abstract**
Here, we simulate a unitary quantum perceptron with quantum computing. The quantum perceptron can be implemented as a single (fast) adiabatic passage in a model of interacting spins. To demonstrate the learning ability of the quantum perceptron, we train it to perform the XOR gate and discuss its power consumption.

**Relevant links**
link to demo:
https://github.com/KaterinaGratsea/Unitary_quantum_perceptron

link to papers:
https://iopscience.iop.org/article/10.1209/0295-5075/125/30004
https://www.nature.com/articles/nphys2385
https://arxiv.org/abs/2111.08977
https://www.nature.com/articles/s41586-019-1666-5#Abs1
https://arxiv.org/abs/2111.09241
https://www.nature.com/articles/s41565-021-00874-8
https://arxiv.org/abs/2103.16726
https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.2.040335

**Comment by CatalinaAlbornoz** [comment]
Hi @KaterinaGratsea, thanks for creating this demo! We will review it and let you know when it's up on the website.

**Comment by KaterinaGratsea** [comment]
Perfect, thanks.

I also have the brief bussiness pitch in the git folder. I realized
afterwards it would have been better if I had simply added it with a
hyperlink in the hackathon project description.

**Comment by CatalinaAlbornoz** [comment]
This is a super interesting demo @KaterinaGratsea. Congratulations! I was happy to see such big energy efficiencies. It's great that you included this in the demo.
About the business pitch, you can remove it in April if you want. We should be making the demo public on the PennyLane website this week. I'll let you know when it's up!

**Comment by CatalinaAlbornoz** [comment]
Hi @KaterinaGratsea, your demo is up on the [PennyLane website](https://pennylane.ai/qml/demos_community.html)! We will be promoting it on Twitter today or tomorrow. Congrats on this amazing demo!

**Comment by KaterinaGratsea** [comment]
Hi Catalina,

great, thanks! Happy to hear that you found it interesting as well!

Have a nice day,
Katerina

**Comment by KaterinaGratsea** [comment]
Hi again,

I am also a bit worried if the business pitch will be taken under
consideration, since I uploaded it on github and not on the project
description when I created a hackathon issue. I have another presentation
there, which is supposed to be the non-technical presentation requested for
the hackathon. Any idea to whom I could write to make clear where the
business pitch is located?

**Comment by CatalinaAlbornoz** [comment]
Hi @KaterinaGratsea, the reviewers for the hackathon project went through the different files on the GitHub so rest assured that they saw your business pitch and presentation.

**Comment by KaterinaGratsea** [comment]
Perfect, thanks for letting me know!
