### ISSUE TITLE
[DEMO] Simulated Annealing

### ISSUE THREAD

**Issue by maxwell04-wq** [PennyLaneAI/qml#513]
#### General information

**Name**
Mahnoor Fatima.

**Twitter** 
@MahnoorTheJack

**Image** 
![5af21e58-196a-43cb-9075-c1fb728e91e0](https://user-images.githubusercontent.com/59219220/173956654-150b0b2d-efa8-4601-b886-45e4964bf912.jpg)

--------------------------------------------------------------------------------

#### Demo information

**Title**
Optimizing a Variational Quantum Circuit via Simulated Annealing 

**Abstract**
In this tutorial, a variational quantum circuit is optimized by using simulated annealing. This algorithm returns a stochastic global optima for the optimization problem.

**Relevant links**
Link to tutorial: https://github.com/maxwell04-wq/simulated-annealing-pennylane/blob/main/Simulated_Annealing_Tutorial_Pennylane.ipynb

References: 
- https://www.mathworks.com/help/gads/what-is-simulated-annealing.html#:~:text=Simulated%20annealing%20is%20a%20method,thus%20minimizing%20the%20system%20energy.
- https://projecteuclid.org/journals/statistical-science/volume-8/issue-1/Simulated-Annealing/10.1214/ss/1177011077.full

**Comment by CatalinaAlbornoz** [comment]
Hi @maxwell04-wq, I wanted to let you know that your demo is now on the PennyLane website! Congratulations! You can see it [here](https://pennylane.ai/qml/demos_community.html).
