### ISSUE TITLE
Update key concepts content pages

### ISSUE THREAD

**Issue by mariaschuld** [PennyLaneAI/qml#54]
**Context:** The Key Concepts section has been turned into a glossary, but the content is somewhat out of date. 

For example:

- *Automatic differentiation page*: Delete or improve the delineation to symbolic or numeric differentiation
- *Circuit ansatz*: Differentiate clearly between "template", "ansatz" and "architecture"

[To be continued...]

**Solution:** We should update and extend the pages one-by-one.

**Comment by glassnotes** [comment]
Following the completion of #135 and #193, the page of automatic differentiation has been removed from view, and a number of new pages / definitions were added. The  pages that were *not* modified in those two updates are:
 - [circuit ansatz](https://pennylane.ai/qml/glossary/circuit_ansatz.html)
 - [hybrid computation](https://pennylane.ai/qml/glossary/hybrid_computation.html)
 - [parameter-shift](https://pennylane.ai/qml/glossary/parameter_shift.html)
 - [quantum embedding](https://pennylane.ai/qml/glossary/quantum_embedding.html)
 - [quantum gradient](https://pennylane.ai/qml/glossary/quantum_gradient.html)
 - [quantum neural network](https://pennylane.ai/qml/glossary/quantum_neural_network.html)
 - [variational circuit](https://pennylane.ai/qml/glossary/variational_circuit.html)

Do you feel any of those pages would benefit from a refresh? If not, we can close this issue.

**Comment by mariaschuld** [comment]
Yes, I thnk this issue is outdated and was not very informative to begin with.

**Comment by glassnotes** [comment]
Cool, thanks for checking! :+1:
