### ISSUE TITLE
[BUG] Overlapping back relation on Demos page

### ISSUE THREAD

**Issue by Mandrenkov** [PennyLaneAI/qml#569]
#### Issue description

On the QML website, the back relation is sticky. This leads to situations where the UI looks like this:

<img width="1003" alt="Screen Shot 2022-09-12 at 4 13 59 PM" src="https://user-images.githubusercontent.com/5883774/189752173-8df7320d-f098-4871-ab6e-a21288237fe7.png">

* *Expected behavior:* The back relation does not overlap with the "Featured" carousel. This means that either the back relation should either not be sticky on the Demos page _or_ the carousel on the Demos page is trimmed to fit the center column of the page.

* *Actual behavior:* The back relation overlaps with the **Featured** carousel.

* *System information:* Windows 10 Version 21H1 / Brave v1.43.89 (64-bit)

#### Source code and tracebacks

N/A

#### Additional information

N/A

**Comment by KetpuntoG** [comment]
Not a problem anymore :)
