### ISSUE TITLE
[DEMO] Generalization of Quantum Metric Learning Classifiers

### ISSUE THREAD

**Issue by Rlag1998** [PennyLaneAI/qml#582]
#### General information

**Name**
Jonathan Kim; Stefan Bekiranov

**Affiliation** (optional)
Research & Development Tech Innovation Hub, GlaxoSmithKline; Department of Biochemistry and Molecular Genetics, University of Virginia

--------------------------------------------------------------------------------

#### Demo information

**Title**
Generalization of Quantum Metric Learning Classifiers

**Abstract**
This demo is a fork of the previously discontinued Embeddings & Metric Learning demo authored by Maria Schuld and Aroosa Ijaz in 2020. This new demo uses the ImageNet ants/bees image dataset and the UCI ML Breast Cancer (Diagnostic) Dataset to assess the generalization limits and performance of quantum metric learning. Schuld and Ijaz's original code was adapted in numerous ways to attempt to produce good test set results for both datasets. The ants/bees dataset, which had a high number of initial features per sample, did not lead to good generalization. Models generalized best for test data when a fewer number of features per sample were used (as seen in the breast cancer dataset), particularly after feature reduction through principal component analysis. Ultimately, this demo illustrates that quantum metric learning can lead to accurate test set classification given a suitable dataset and appropriate data preparation.

**Relevant links**
Associated manuscript submitted to Biomolecules: "_Generalization Performance of Quantum Metric Learning Classifiers_"
GitHub Repository for Demo: https://github.com/Rlag1998/QML_Generalization
"_Quantum Embeddings for Machine Learning_" by Lloyd et al. (2020): https://arxiv.org/abs/2001.03622
"_Transfer learning in hybrid classical-quantum neural network_" by Mari et al. (2019): https://arxiv.org/abs/1912.08278

**Comment by CatalinaAlbornoz** [comment]
Hi @Rlag1998, this is amazing work! We will review it and get back to you. Thank you for this amazing contribution!
