### ISSUE TITLE
[BUG] "View on GitHub" links broken on demo pages

### ISSUE THREAD

**Issue by ikurecic** [PennyLaneAI/qml#591]
#### Issue description

* *Expected behavior:* "View on GitHub" links to source file on GitHub

* *Actual behavior:* Links don't include organization and repository (PennyLaneAI/qml). Example link: https://github.com//blob/master/demonstrations/tutorial_vqe.py on https://pennylane.ai/qml/demos/tutorial_vqe.html

**Comment by josh146** [comment]
Thanks to @LucasSilbernagel, this should now be fixed :)
