### ISSUE TITLE
[DEMO] Perturbative Gadgets for Variational Quantum Algorithms

### ISSUE THREAD

**Issue by SimonCichy** [PennyLaneAI/qml#593]
#### General information

**Name**
Simon Cichy.

**Affiliation** (optional)
Dahlem Center for Complex Quantum Systems, Freie Universität Berlin, 14195 Berlin, Germany,
Institute for Theoretical Physics, ETH Zürich, 8093 Zürich, Switzerland.

**Twitter** (optional)
@sdcichy

**Image** (optional)
![FC_gadget-terms-tutorial](https://user-images.githubusercontent.com/70891818/194835565-c27a0e4b-f66f-486d-8704-ca49f37ebf8b.png)

--------------------------------------------------------------------------------

#### Demo information

**Title**
Perturbative Gadgets for Variational Quantum Algorithms

**Abstract**
In this tutorial, we will explore the application of perturbative gadgets in variational quantum algorithms. Substituting a global Hamiltonian with its gadgetized equivalent allows to train the algorithm on a local cost function and still finding the target minimum, thus avoiding the issue of cost function dependent barren plateaus.

**Relevant links**
https://github.com/SimonCichy/barren-gadgets/tree/main/Pennylane-tutorial
https://arxiv.org/pdf/2210.03099.pdf

**Comment by isaacdevlugt** [comment]
Thanks @SimonCichy ! Look forward to checking this out 👀

**Comment by KetpuntoG** [comment]
Hi @SimonCichy , great job! The demo is really well done 😄 If you like we could guide you to introduce it as a demo of the pennylane website with your name, instead of in the community demos section.  This requires a bit more work and will take a bit more time but I wanted to tell you about the option in case you find it interesting 💪 If not, we will get on with the integration in the community section 🚀

**Comment by SimonCichy** [comment]
Hi @KetpuntoG, thanks a lot, it is nice to hear that 😄 And in principle, I would be happy to make it a demo of the pennylane website! If you can tell me a bit more about what it implies, what would have to be changed, etc, I could tell you if (or rather how quick) I can do it

**Comment by KetpuntoG** [comment]
The steps to write a demo in PennyLane can be found in the readme of the [qml repo](https://github.com/PennyLaneAI/qml). The format of the demos are in `.py` using Sphinx. Having the notebook already made, we have a script (in the readme you will find it too) to facilitate the conversion. Then, it's just a matter of fixing small formatting details. Once you have it in demo format, we will do a more in-depth review of the content in which we will do a couple of interactions with you. Estimating more or less the time, from the moment you start building the demo until it goes through the review process, it could be a month. If you are in a hurry, we can always put the demo as a community demo and then, when you prefer, work on the PennyLane proper demo. How do you want to proceed? :) 

Translated with www.DeepL.com/Translator (free version)

**Comment by josh146** [comment]
@SimonCichy something to note is that our demos are not in the form of notebooks. Instead:

- They are executable python scripts
- The text describing the code is using [restructuredText](https://bashtage.github.io/sphinx-material/basics.html), not markdown

But there are nice ways to convert a notebook to this format. For example, you can export a notebook in `rst` format (and then manually change it to a python script) directly from Jupyter: 

![image](https://user-images.githubusercontent.com/2959003/195699813-13c69e2a-cd0d-4de3-b184-ea259d6d7397.png)

Alternatively, we have a [script linked in the readme](https://gist.github.com/chsasank/7218ca16f8d022e02a9c0deb94a310fe) for converting jupyter notebooks.

**Comment by SimonCichy** [comment]
Thank you both! I am not in a hurry, and it does not seem to be all too much work, so I'm in. I will get working on converting the file and will let you know when it is done, or if I am having issues.

**Comment by SimonCichy** [comment]
I believe I have done the necessary changes, but I would be happy if you could confirm the next steps. 
I have now the qml repo locally and have added my tutorial in .py format in demonstrations. It runs the way it is supposed to, but I didn't know where to put the other files (where I define things which I did not want to go into detail in the tutorial itself). For now, I put them in the subfolder corresponding to the tutorial (where I also put the image from the tutorial). Is it fine like that?
To check that everything is in order, I tried to build the website locally (running only my demo, as explained in the readme) but I am having issued with that. Should I still do the pull request as is?

**Comment by josh146** [comment]
@SimonCichy awesome to hear! Definitely feel free to open a PR, that is much easier than building the website locally.

When you create a PR, we have an automatic build system that will build the website, and create a link in the PR for you to view the changes. This preview will update with every push to the PR :)

**Comment by SimonCichy** [comment]
To be honest, it will be my first pull request, so could you confirm, that I am doing it right before I mess something up? (sorry)
I cloned the repository, created a branch (local for now) and did my changes there. Do I push to make it a remote branch, and then proceed to making a PR from my (new) branch to the master branch? Thanks for the help...

**Comment by isaacdevlugt** [comment]
Yep! Just push your changes: `git push --set-upstream origin <branch name>`, then make a Pull Request 😄. The Pull Request will be for merging your branch with your demo into the `master` branch 🙂. See [here](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request) for making a Pull Request! Let us know if you have any issues with that 🚀

**Comment by SimonCichy** [comment]
Thank you a lot. Apparently, I do not have the correct access rights, so I guess I am doing something wrong. When trying to set the upstream branch on the terminal, I get an error message 
```
Permission denied (publickey).
fatal: Could not read from remote repository.      
Please make sure you have the correct access rights
and the repository exists
```
When doing it with my git GUI, after a few seconds the remote branch disappears and checking the status I get 
```
Your branch is based on 'origin/demo_barren_gadgets', but the upstream is gone.
```
I will try to investigate what went wrong, but if it is a problem you are familiar with, I would appreciate some advice 😉

**Comment by isaacdevlugt** [comment]
🤦! Sorry about that @SimonCichy, should've known you wouldn't have had permissions. 

As @KetpuntoG said, if you _fork_ the repo, make your changes _there_, then make a PR from your forked version, then you're all set! 

Instructions [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by SimonCichy** [comment]
Thank you a lot, again. Now there should be a pull request, but most of the checks were not successful. Does that mean something went wrong on my side?

**Comment by josh146** [comment]
@SimonCichy perfect, now we can jump into the PR and help troubleshoot :)

**Comment by KetpuntoG** [comment]
I close this issue, we are already working with the proper demo
