### ISSUE TITLE
[BUG] Wrong image on tutorial classical kernels

### ISSUE THREAD

**Issue by emgilfuster** [PennyLaneAI/qml#608]
#### Issue description

* *Expected behavior:* The first image in https://pennylane.ai/qml/demos/tutorial_classical_kernels.html should be https://github.com/PennyLaneAI/qml/blob/master/demonstrations/classical_kernels/flowchart.PNG

* *Actual behavior:* The first image in https://pennylane.ai/qml/demos/tutorial_classical_kernels.html is https://github.com/PennyLaneAI/qml/blob/master/demonstrations/quantum_analytic_descent/flowchart.png

#### Additional information

I looked into the python file (https://github.com/PennyLaneAI/qml/blob/master/demonstrations/tutorial_classical_kernels.py) from where the rst file is created, and the image address is correctly written there.
I tried to rename the image and use the new name in the python file, but then I can't build the site locally with sphinx anymore, there must be another reference to the image name somewhere that I don't understand.

**Comment by josh146** [comment]
Hey @emgilfuster, I have a feeling this is because Sphinx -- when processing images -- is not case sensative 🤔 So the `.png` and `.PNG` is not properly differentiated.

A fix could be to give the two images different names

**Comment by emgilfuster** [comment]
Thanks @josh146! I tried to fix it that way but sphinx failed to build locally. Maybe I did something wrong, I'll try again

**Comment by CatalinaAlbornoz** [comment]
Thanks for taking care of this @emgilfuster!

**Comment by KetpuntoG** [comment]
Hey @emgilfuster 👋 once you have done the PR, this rocket will appear below, just click on "view deployment".
Let us know if you have any problems :) 


![Captura de Pantalla 2022-11-29 a las 12 24 46](https://user-images.githubusercontent.com/65235481/204599280-7ee5b222-1d1f-4300-91fb-2c92c4d23ade.png)

**Comment by emgilfuster** [comment]
Hi! Thanks, I'm sorry, I'm struggling to find a moment of peace for this.
I'll let you guys know, hopefully soon!

**Comment by emgilfuster** [comment]
Hi!
Sorry for my novice-ness, I created a pull request #657
Where am I supposed to see the built version @josh146, to see that everything went smoothly?

Thanks!

**Comment by KetpuntoG** [comment]
Thanks for the PR @emgilfuster ! There seems to be a problem and it does not pass the tests. At the bottom of the PR you can see it. If the tests pass, a button with a rocket will appear to see the changes. I'll take a look to see why you are getting the error

**Comment by emgilfuster** [comment]
Thanks for the very quick response @KetpuntoG.
I notice my PR is very muddy because of former PRs, would I make your life easier if I erase my existing fork and make a new one from scratch? Then there would be fewer commits that could be the source of the problems.
Sorry that solving this takes your time too.

**Comment by KetpuntoG** [comment]
problem solved in [this PR ](https://github.com/PennyLaneAI/qml/pull/657) 🚀
