### ISSUE TITLE
[DEMO] Generalization of Quantum Metric Learning Classifiers

### ISSUE THREAD

**Issue by Rlag1998** [PennyLaneAI/qml#615]
#### General information

**Name**
Jonathan Kim; Stefan Bekiranov.

**Affiliation** (optional)
R&D Tech, GlaxoSmithKline; Department of Biochemistry and Molecular Genetics, University of Virginia.

**Image** (optional)
https://github.com/Rlag1998/QML_Generalization/blob/main/embedding_metric_learning/figures/All_Figures/3.4.2.png?raw=true

--------------------------------------------------------------------------------

#### Demo information

**Title**
Generalization of Quantum Metric Learning Classifiers

**Abstract**
This demo is a fork of the previously discontinued Embeddings & Metric Learning demo authored by Maria Schuld and Aroosa Ijaz in 2020. This new demo uses the ImageNet ants/bees image dataset and the UCI ML Breast Cancer (Diagnostic) Dataset to assess the generalization limits and performance of quantum metric learning. Schuld and Ijaz's original code was adapted in numerous ways to attempt to produce good test set results for both datasets. The ants/bees dataset, which had a high number of initial features per sample, did not lead to good generalization. Models generalized best for test data when a fewer number of features per sample were used (as seen in the breast cancer dataset), particularly after feature reduction through principal component analysis. Ultimately, this demo illustrates that quantum metric learning can lead to accurate test set classification given a suitable dataset and appropriate data preparation.

**Relevant links**
Associated paper, "Generalization performance of quantum metric learning classifiers": https://doi.org/10.3390/biom12111576
GitHub Repository for Demo: https://github.com/Rlag1998/Embedding_Generalization
"Quantum embeddings for machine learning" by Lloyd et al. (2020): https://arxiv.org/abs/2001.03622
"Transfer learning in hybrid classical-quantum neural network" by Mari et al. (2019): https://arxiv.org/abs/1912.08278

**Comment by CatalinaAlbornoz** [comment]
Hi @Rlag1998, thank you for working on this this demo! It looks like amazing work. We will be reviewing it and letting you know of any next steps soon.

**Comment by KetpuntoG** [comment]
Hey @Rlag1998 ! Everything is ready and this Thursday we will publish the demo 😄 
If you have a twitter account we could mention you on the tweet

**Comment by Rlag1998** [comment]
Hi @KetpuntoG, thank you again for getting it all ready!

Maybe this Twitter account could be mentioned: [@Jonathan_Kim_98](https://twitter.com/Jonathan_Kim_98)

Thanks! 😄

**Comment by CatalinaAlbornoz** [comment]
Awesome @Rlag1998!
