### ISSUE TITLE
Multiclass margin classifier demo has a very long execution time

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/qml#68]
The [Multiclass margin classifier](https://pennylane.ai/qml/demos/tutorial_multiclass_classification.html) currently takes 18 minutes to execute, which is significantly too long (in the readme, we recommend no longer than 10 minutes at most).

If there is no performance optimization we can make to the code, I recommend we convert it into a non-executable tutorial, similarly to the [QNN function fitting demo](https://pennylane.ai/qml/demos/quantum_neural_net.html).

This involves:

* Removing `tutorial_` from the filename

* Hardcoding in the output as a Python comment, like so:

```python
##############################################################################
# .. rst-class:: sphx-glr-script-out
#
#  Out:
#
#  .. code-block:: none
#
#     First X sample (original)  : tensor([5.1000, 3.5000, 1.4000, 0.2000], dtype=torch.float64)
#     First X sample (normalized): tensor([0.8038, 0.5516, 0.2206, 0.0315], dtype=torch.float64)
#     Num params:  111
#     Iter:     1 | Cost: 0.3920648 | Acc train: 0.6428571 | Acc test: 0.5789474
#     Iter:     2 | Cost: 0.4511958 | Acc train: 0.3392857 | Acc test: 0.3157895
#     Iter:     3 | Cost: 0.3106308 | Acc train: 0.3392857 | Acc test: 0.3157895
```

* Saving the generated plot, and hardcoding it into the Python script.

**Comment by mariaschuld** [comment]
We could simply use 50 instead of 100 optimisation steps, which should make things twice as fast. The final plot is quite noisy anyways!

@thisac are you still upgrading this demo to tape mode, so that you could change `total_iterations = 100` to `total_iterations = 50`? Or shall I make a PR?

**Comment by josh146** [comment]
The new backprop default might make a big difference without any changes, even?

**Comment by glassnotes** [comment]
@antalszava has updated this one to tape mode. The new version takes between 7-8 minutes on my machine, I expect it will build for the demo page in ~10 minutes which is much better than before!

**Comment by glassnotes** [comment]
The build in tape mode confirms the demo time is now down to ~7.5 minutes. It may be possible to improve this further, but will close this now since this is a significant improvement and the build time is now below the recommended threshold.
