### ISSUE TITLE
[DEMO] Contextuality and inductive bias in machine learning

### ISSUE THREAD

**Issue by josephbowles** [PennyLaneAI/qml#722]
#### General information

**Name**
Joseph Bowles

**Image** 
see thumbnail in demonstrations/contextuality

--------------------------------------------------------------------------------

#### Demo information

**Title**
Contextuality and inductive bias in quantum machine learning 

**Abstract**
This is a demo for my recent paper https://arxiv.org/abs/2302.01365

In the demo we study the toy learning problem described in the paper, and build and train a quantum model that encodes the relevant inductive bias. The model is shown to outperform a 'generic' quantum model that does not encode this bias.

The demo is not focused much on contextuality (because it would require a lot of explanation), but rather focuses on the type of learning problem (inspired from contextuality) that is presented in the paper.

JAX is used for vectorization and JIT compilation.

**Relevant links**
https://github.com/PennyLaneAI/qml/pull/719  (see latest build)

**Comment by KetpuntoG** [comment]
Hey @josephbowles  😄 we do not usually open issues of this type, does this mean that it is ready for review?

**Comment by KetpuntoG** [comment]
Awesome, thanks!
I'll close the issue then. We will now go through at least two people to take a look at the demo. I am in charge of informing the reviewers (of which I want to be one 😉)
