### ISSUE TITLE
Consider using the latest Mitiq version

### ISSUE THREAD

**Issue by andreamari** [PennyLaneAI/qml#783]
In [`requirements_no_deps.txt`](https://github.com/PennyLaneAI/qml/blob/master/requirements_no_deps.txt) Mitiq is pinned to a quite old version `0.13.0` .
Unless there are drawbacks, I would suggest one of the following two options:

1. Avoid pinning the version of `mitiq` in `requirements_no_deps.txt`.
2. Pin `mitiq` to the latest stable version

**Comment by KetpuntoG** [comment]
Thank you for opening this issue! I will check that with the latest version (0.25.0) everything is still working. Is that ok?

**Comment by andreamari** [comment]
Sounds good, thanks!

**Comment by KetpuntoG** [comment]
Updated, everything works as expected 😄
Thanks @andreamari! I close the issue

**Comment by andreamari** [comment]
Thank you, @KetpuntoG !
