### ISSUE TITLE
Add a banner on the home page, with 'Start here' links

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/qml#83]
With no organization on the 'Demos' page, it is difficult for new users to identify exactly where they should start. There are a couple of potential solutions.

* Add a banner on the home page, with 'Start here' links. Something similar to the following?

  ![image](https://user-images.githubusercontent.com/2959003/81773990-bbc98c80-9528-11ea-926b-41a1289c2e02.png)

* Start organizing the demos?

* Keep the demos as is, but 'Feature' some demos at the top of the page (similar to the home page carousel).

**Comment by glassnotes** [comment]
Is this still something we want? I can add it to the [demos entry page](https://pennylane.ai/qml/demonstrations.html) directly above (or below) the "basic", "research", and "community" cards.

**Comment by josh146** [comment]
Good question. This issue was made before we (re)categorized the demos page into separate 'basics' and 'research' pages.

The example in the top comment is taken from https://strawberryfields.ai/photonics/. Should we do something similar here still?

**Comment by glassnotes** [comment]
I think it would be nice to have somewhere near the top of the main demo page to get peoples attention, but I also wouldn't want it to be too obtrusive since there are is the community banner and featured demo carousel. Maybe it would be good as a dropdown sphinx element?

**Comment by glassnotes** [comment]
We've decided to close this as per discussion in #159  as it is no longer relevant after redesign.
