### ISSUE TITLE
[BUG] Full author list not appearing for demos on Xanadu website

### ISSUE THREAD

**Issue by jackbaker1001** [PennyLaneAI/qml#861]
-------------------------------------------------------------------------------------------------------------

#### Issue description

I wrote a demo a while back for this repository and just noticed that, despite the code here still including me as an author with all the relevant details, the website no longer displays my name/details.

See: https://pennylane.ai/qml/demos/tutorial_univariate_qvr

This may not be an isolated incident.

Any thoughts @KetpuntoG ?

**Comment by josh146** [comment]
Thanks @jackbaker1001 for catching this! We just pushed a logic change to our website regarding loading author data, and it looks like this may have affected some multi-author demos. We're looking into this now and will let you know when it's fixed :+1:

**Comment by KetpuntoG** [comment]
Hey @jackbaker1001 ,It has been solved ([demo](https://pennylane.ai/qml/demos/tutorial_univariate_qvr)) 😄
Thank you for letting us know!
